
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSmQ3YVBXb2xKMlF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBek1qUXlNek0yTlRSYUZ3MHpOVEF6TWpJeU16UXhOVFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN1M24veHZpZHZ5NmJkcldtU2hqM1Z4a0VEVm91ZGhqMHBGbkVkMnR1OHhGaGcvamg1VDBFamQ1dloKNDQ1NTQ1c3lPd1RvMEpsWFMwSzJ5dSt6NnlNQUFJTFBpcTlSdE5uNU9qVmNORjZBOTFpaUJtb0xuSDV4WVZ5MApQSmx3ZURiL0pseU92dzZvak1wTlpiVzVpRlYrN1A2YjMwNTRXUnQydm9FM2EzOXA3Yi9pN3Npa08yc0RVMGVZCjNFakE2WVMxSHJQdERkaHhEdk56NUpNTVViTVR5S0FtT1JaZ0YwaGF6YnAyY0w0MVVvM3drMTZqZDk2ZitsQzUKZk1nSUdJVmlSb3FoVFFyNk9CN2V4NjZpMlhSaHJQbWdTZDlkdnBHSXUxSHhGU3NGb2ZueGpoRGNlaG4rckMyQwp4MlJXemNEa3h5SWJnWXJHWlc4bDlzTkdqT0dCQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUOEIzVHhiMEZDTWI1NGx3OGJ3cVBKY1psSHZUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0hkOFFPWUJwawpoL3JGcUN1R0JLUUlOZ3hjRWJBMkNYcU9la0YxQXdrTjRQcHFlUlYvS2dQajJoMzNuSFhZdFRBcEZXb002UFJQCmxTbWxwQTlEdjYzSTlOQ25YVldsT1M0Z3IzV2V2ZTBoa1Uwa2hxcVdUNUlPekJjRHZGRlc0UHdQVkJSd0VzTFIKUCtlYmY3UHF6NE9YS3dTUlpEd21vWktJUE1tV21iRWhVSEFCRnlXbmpieUNsVjFOM1ZyNTBqcS82U3R1VS95TQorQTltQUp4WmRXTnF3U1dUdXdjSzFHVWpoejFoc2JoMkZZcUsxMEZLQjdDRUhtVnVMaG9sbTUrbnF4UUhuYm5tCkZteWVKSEd0WWJuNTNJL29ncjhSTGxzZmdlaDE4OUgzaEFRWXh2Y1NQSHIybzUrNE5RM2J6L3FWMlZmaERPaWYKaXFrWjErWDFTZ2tJCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://1600ad32-9ff0-48e6-a8f2-a1cfde0a6fd4.eu-central-3-gw.linodelke.net:443
  name: lke381733

users:
- name: lke381733-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlV6Sm9VdkQ4c295VHNoZEJMd0x3M2NlWHZNcHM2Zk9sQlpWQnlJRG1mekUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tNmZoZ2IiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYzc0M2MzNTAtMzc4MS00Nzg5LTliMGYtYTkwYjIxYjljYTE4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.CaymB9ie_MAcSlj2nD0KufmwMGjsC9UtoaMKqiLTsjfGiv04511UMOzK8-TxTHEmIWOBSZAr6daH5sMjhdbh3r9KA5JUE7ejsVZTn6c0S2EiELEgYO4gTjlAfzx9KHi5iZJDcRXaxMIGG3PJ1UD0QBS3A_JMkQlrnIFWhwWt4dUMD9yYOgV_nGzsU3zx_vN3GaSepcd6iGlXAXUfw9wHxeAfjAp_djONNpHxf4NFSDGCmg8UU8leKyzfOU4OkZLXgaXWlP5R6JSVvgFqrgwinTEyvTcJFC6BBUM3A8v8FMC__8WM8xvrBWUbx5TSTkBvGeUl-A2Q1WzxaermlEdKIw

contexts:
- context:
    cluster: lke381733
    namespace: default
    user: lke381733-admin
  name: lke381733-ctx

current-context: lke381733-ctx
